spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: id-to-google
            client-secret: secret-to-gooble
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com  
